import math


# game settings
RES = WIDTH, HEIGHT = 1200, 600
FPS = 60
HALF_WIDTN = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

# player settings
PLAYER_POS = 3, 4 # Позиция игрока 
PLAYER_ANGLE = 0 # Угол игрока
PLAYER_SPEED = 0.004 # Скорость игрока
PLAYER_POT_SPEED = 0.002 # Скорость врачения игрока
PLAYER_SIZE_SCALE = 60

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RAGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

# raycating settings
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20 


# 3D settings
SCREEN_DIST = HALF_WIDTN / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2 